import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { useT } from '../lib/i18n';

export default function Terms() {
  const t = useT();

  return (
    <motion.div
      initial={{ opacity: 0, y: 8 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.3 }}
      className="min-h-dvh p-6 md:p-12 max-w-3xl mx-auto"
    >
      <Link to="/" className="text-rihla-muted text-sm hover:text-rihla-text">{t('privacy.back')}</Link>

      <h1 className="font-display text-4xl text-rihla-text mt-6 mb-2">{t('terms.title')}</h1>
      <p className="text-rihla-muted text-sm mb-10">{t('terms.lastUpdated')}</p>

      <section className="space-y-8 text-rihla-text/90 leading-relaxed">
        <div>
          <h2 className="font-display text-xl text-rihla-text mb-3">About Rihla</h2>
          <p className="text-sm">
            Rihla is an AI-powered travel planning service that helps users discover and plan personalized journeys. The service is provided on an anonymous basis — no account creation or personal identification is required.
          </p>
        </div>

        <div>
          <h2 className="font-display text-xl text-rihla-text mb-3">Use of Service</h2>
          <p className="text-sm">
            By using Rihla you agree to use the service solely for personal, non-commercial travel planning purposes. You may not use the service to generate content that is harmful, misleading, or in violation of applicable law.
          </p>
        </div>

        <div>
          <h2 className="font-display text-xl text-rihla-text mb-3">Anonymous Sessions</h2>
          <p className="text-sm">
            Each visit creates an anonymous session identified by a randomly generated ID stored in your browser. No name, email, or payment information is required. Session data is used solely to power the conversation and generate your itinerary. You may delete your session data at any time via the <Link to="/privacy" className="text-rihla-accent hover:text-rihla-gold transition-colors">Privacy</Link> page.
          </p>
        </div>

        <div>
          <h2 className="font-display text-xl text-rihla-text mb-3">AI-Generated Content</h2>
          <p className="text-sm">
            Itineraries and travel recommendations are generated by AI and are provided for informational and planning purposes only. Rihla does not guarantee the accuracy, availability, or pricing of any destination, activity, accommodation, or service mentioned. Always verify details independently before booking.
          </p>
        </div>

        <div>
          <h2 className="font-display text-xl text-rihla-text mb-3">Intellectual Property</h2>
          <p className="text-sm">
            The Rihla brand, interface, and underlying technology are the property of Rihla and its licensors. AI-generated itinerary content is provided to you for personal use. You may not reproduce, redistribute, or commercialize itinerary content without written permission.
          </p>
        </div>

        <div>
          <h2 className="font-display text-xl text-rihla-text mb-3">Limitation of Liability</h2>
          <p className="text-sm">
            Rihla is provided "as is" without warranty of any kind. To the fullest extent permitted by law, Rihla shall not be liable for any indirect, incidental, or consequential damages arising from your use of the service, including but not limited to travel disruptions, booking errors, or reliance on AI-generated recommendations.
          </p>
        </div>

        <div>
          <h2 className="font-display text-xl text-rihla-text mb-3">Changes to These Terms</h2>
          <p className="text-sm">
            We may update these Terms from time to time. Continued use of the service after any changes constitutes your acceptance of the updated Terms. The date at the top of this page indicates when these Terms were last revised.
          </p>
        </div>

        <div>
          <h2 className="font-display text-xl text-rihla-text mb-3">Governing Law</h2>
          <p className="text-sm">
            These Terms are governed by the laws of the Kingdom of Saudi Arabia. Any disputes shall be resolved in the courts of Saudi Arabia.
          </p>
        </div>

        <div>
          <h2 className="font-display text-xl text-rihla-text mb-3">Contact</h2>
          <p className="text-sm">
            For questions about these Terms, contact <span className="text-rihla-accent">legal@rihla.example</span>.
          </p>
        </div>
      </section>

      <div className="mt-12 pt-8 border-t border-white/5 flex gap-6 text-xs text-rihla-muted">
        <Link to="/privacy" className="hover:text-rihla-text transition-colors">{t('nav.privacy')}</Link>
        <Link to="/pricing" className="hover:text-rihla-text transition-colors">{t('nav.pricing')}</Link>
      </div>
    </motion.div>
  );
}
